### PR TITLE
Brunswick Eruption Changes

### PR DESCRIPTION
**Pull request by anglesideangle**
WOOOOOOOOOOOOOOOOOO

### CODE REVIEW

**Comment by dhinakg** [comment]
Nice

**Review by dhinakg — APPROVED** [review]

**Comment by NebuDev14** [comment]
W

**Review by lee-H1208 — APPROVED** [review]
🤩

**Comment by avsnr** [comment]
Update 3 ball paths

**Comment by avsnr** [comment]
Modified auto

**Pull request merged**
